title: Ahis virtuel room
author: ahibaba
email: ahmeetselman@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is a fun blog page of Ahmet Selman. Just to work out how GitHub pages works lol

# social links
github_username:  ahmtslmngcl # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
